### ISSUE TITLE
In-game reloading of adjusted config parameters

### ISSUE THREAD

**Issue by AlteOgre** [Lembas-Modding-Team/pvp-mode#171]
Assuming the mod needs to reload after a config value of parameter has been changed, I usually use a restart. To enhance user friendliness, we could add a command that activates effective re-loading of all config input to the mod. Possible command: '/pvpadmin reload'.

**Comment by CraftedMods** [comment]
I suggest `pvpconfig reload`. We already have pvpconfig. But some configuration entries require a server restart. It's planned to allow the modification if configuration entries via `pvpconfig`. Every entry that's modifiable with this command, is also reloadable.

**Comment by CraftedMods** [comment]
We add a `ConfigReload` event, which can be used by compatibility modules to reload other configuration files, to example the biome override configuration (which isn't managed by the default configuration system of the PvP Mode Mod).
