### ISSUE TITLE
Compatibility with Custom Enchantments plugin.

### ISSUE THREAD

**Issue by AlteOgre** [Lembas-Modding-Team/pvp-mode#274]
Please cover compatibility with this plugin:
https://dev.bukkit.org/projects/custom-enchantments/pages/all-enchantments
Make the partial inventory drop exclude items with the Autorepair aspect from this plugin.
Configurable ofc. and for the time being only connected to the 'Autorepair' attribute.

**Comment by CraftedMods** [comment]
To make the support more abstract, I'll add a configuration file where on can specify the enchantements with which the items won't be dropped.

**Comment by AlteOgre** [comment]
More concrete.

**Comment by CraftedMods** [comment]
More abstract, because all enchantements are supported instead of one.

**Comment by CraftedMods** [comment]
As the PvP Mode Mod will have a soulbound feature, we don't have to support the plugin.
