### ISSUE TITLE
Crash with deathcraft and lotr bounty.

### ISSUE THREAD

**Issue by DwarfyAssassin** [Lembas-Modding-Team/pvp-mode#283]
So I had a bounty on a player and when I killed him it crashed the server. It seems like it has to do with the compabiblity module form deathcraft. It's a thermos server  running the  latest version of lotr and v1.4.1-beta of pvp-mode.
Here are the crash report and the consol log
[Akliz Command Center - _lotr_crash-reports_crash-2018-09-29_07.57.56-server.txt](https://github.com/Lembas-Modding-Team/pvp-mode/files/2430481/Akliz.Command.Center.-._lotr_crash-reports_crash-2018-09-29_07.57.56-server.txt)
[new 1.txt](https://github.com/Lembas-Modding-Team/pvp-mode/files/2430482/new.1.txt)

**Comment by CraftedMods** [comment]
It seems like it's the same cause as with the crash for empty inventories, which will be fixed with `1.5.0-BETA`.
