### ISSUE TITLE
Unstackable items after soulbound

### ISSUE THREAD

**Issue by DwarfyAssassin** [Lembas-Modding-Team/pvp-mode#290]
If you add soulbound and remove soulbound from an item it doesn't stack with items which have never been soulbound.
My guess is that the unsoulbound item still has a nbt tag like `Soulbound: 0` While the item which was never soulbound doesn't have that tag.

**Comment by CraftedMods** [comment]
I'll take a look in a week, when I've vacation. Maybe @AlteOgre wants to verify the issue?
