### ISSUE TITLE
Visible Soulbound tag

### ISSUE THREAD

**Issue by AlteOgre** [Lembas-Modding-Team/pvp-mode#291]
The mod's Soulbound tagging feature is effective, but for players it is not visible whether an item is Soulbound or not. A simple identifier showing up when watching an item should do, in the same way that it is implemented in SuffixForge.

**Comment by CraftedMods** [comment]
Are you sure? The feature is definetely implemented.

**Comment by AlteOgre** [comment]
Yes. Just got it confirmed it again. Odd.

**Comment by DwarfyAssassin** [comment]
Alte what do you mean the soulbound lore tag? Because the soulbound lore tag is working fine for me.

**Comment by CraftedMods** [comment]
I cannot confirm this issue too. For `2.0.0-BETA` it definetely works again. Therefore I'm closing this issue now.
