### ISSUE TITLE
Soulbound crash with partial inventory loss/keeyInventory disabled

### ISSUE THREAD

**Issue by DwarfyAssassin** [Lembas-Modding-Team/pvp-mode#311]
If you have keepinv false and with partial inv drop and a soulbound item in your inv and you die you get a internal server error and all your items disapear even the unsoulbound items.

I have added the latest.log and the config file (in a zip file since you can't send .cfg files)
[latest.log](https://github.com/Lembas-Modding-Team/pvp-mode/files/2728370/latest.log)
.

[pvp-mode.zip](https://github.com/Lembas-Modding-Team/pvp-mode/files/2728365/pvp-mode.zip)

EDIT: This bug was noticed while the development of `2.0.0-BETA`, and it was fixed. For documentation reasons we'll assign it to the relevant milestone. ~CraftedMods

**Comment by CraftedMods** [comment]
I'll take a look at it later. Thanks for reporting it.

**Comment by CraftedMods** [comment]
Ah, I know what you mean. While porting `1.5.0-BETA` to `2.0.0-BETA`, I noticed exactly that bug with the soulbound command. I fixed it then. How servere is that for your server? Do you need a bugfix version, or can it wait until `2.0.0-BETA.1` (that version should be released within the next week)?

**Comment by DwarfyAssassin** [comment]
It's not a problem since I have keep inventory enabled
