### ISSUE TITLE
Crash with v35 on startup.

### ISSUE THREAD

**Issue by DwarfyAssassin** [Lembas-Modding-Team/pvp-mode#354]
It seems that LOTR changed or renamed the main faction class so that means that pvp mode can't find it.
`java.lang.NoClassDefFoundError: lotr/common/LOTRFaction`

It looks like that most of the faction related stuff got moved to the `lotr.common.fac` package instead of `lotr.common.LOTRFaction` class.

Here is a log from one of the wiki discord users who found it.
[latest(3).log](https://github.com/Lembas-Modding-Team/pvp-mode/files/3379085/latest.3.log)

**Comment by CraftedMods** [comment]
Closed with a83bb5012f20f076fb71c36883ffdbb2d627428e
